# The configuration file for the GenAI-MIDI-module

# Metadata about this configuration
title = "RPi U2MIDI Pro: Ableton inputs to outputs"
owner = "Alec Hunter and Charles Martin"
description = "Connects via audio interface to ableton External Instrument tracks"

# Basic config
log = true
log_predictions = false
verbose = true

# Interaction Configuration
[interaction]
mode = "callresponse" # Can be: "callresponse", "polyphony", "battle", "useronly"
threshold = 0.1 # number of seconds before switching in call-response mode
input_thru = false # sends inputs directly to outputs (e.g., if input interface is different than output synth)

# Model configuration
[model]
dimension = 9
file = "models/musicMDRNN-dim9-layers2-units64-mixtures5-scale10.h5"
size = "s" # Can be one of: xs, s, m, l, xl
sigmatemp = 0.01
pitemp = 1
timescale = 1

# MIDI Mapping
[midi]
in_device = "U2MIDI Pro"
out_device = "U2MIDI Pro"
input = [ # nanoKONTROL Studio knobs
  ["control_change", 1, 13], # nanoKONTROL Studio knob controller 1
  ["control_change", 1, 14], # nanoKONTROL Studio knob controller 2
  ["control_change", 1, 15], # nanoKONTROL Studio knob controller 3
  ["control_change", 1, 16], # nanoKONTROL Studio knob controller 4
  ["control_change", 1, 17], # nanoKONTROL Studio knob controller 5
  ["control_change", 1, 18], # nanoKONTROL Studio knob controller 6
  ["control_change", 1, 19], # nanoKONTROL Studio knob controller 7
  ["control_change", 1, 20], # nanoKONTROL Studio knob controller 8
]
output = [ # Collection of Useful Mappings
  ["note_on", 1], # note
  ["control_change", 1, 1], # 
  ["control_change", 1, 2], # 
  ["control_change", 1, 3], # 
  ["note_on", 2], # note
  ["control_change", 1, 4], # 
  ["control_change", 1, 5], # 
  ["control_change", 1, 6], # 
]

[websocket]
server_ip = "0.0.0.0" # The address of this server
server_port = 5001 # The port this server should listen on.